### PR TITLE
Add ScyllaDB to list of supported backends

### PR DESCRIPTION
**Pull request by avikivity**

### CODE REVIEW

**Comment by porunov** [comment]
@avikivity Thanks for the contribution!

There is a requirement that each contributor must sign a CLA. It isn't automate right now but JanusGraph members are working on it.

To contribute you should:
1. Sign a CLA. Instructions are here: https://github.com/JanusGraph/legal/blob/master/README.md
2. Follow this instructions: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md

Tell if you don't want to sign a CLA, in such case, I think janusgraph committers could include ScyllaDB into the list.

Please feel free to ask any questions

**Comment by avikivity** [comment]
I already did this, please check the claim inbox and let me know if something is missing.

**Comment by porunov** [comment]
@pluradj @mbrukman could you please add @avikivity to CLA signers?

**Comment by mbrukman** [comment]
https://github.com/JanusGraph/legal/pull/143 is taking care of the CCLA for ScyllaDB

**Comment by mbrukman** [comment]
@avikivity — you're using your @gmail.com address for the commit, but the CCLA (and your DCO sign-off) uses your @scylladb.com email address, so this will stay `[cla: no]` until that's fixed.

Please see [these instructions][amend-commit] for how to fix your commit in-place, and then `git push -f` this branch.

[amend-commit]: https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md#configure-your-repo-to-match-the-cla

**Comment by avikivity** [comment]
Sorry about that; fixed.

**Pull request merged**
