### PR TITLE
Add Uber logo with link

### PR DESCRIPTION
**Pull request by porunov**
PR should wait for approval for Uber representatives.

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
We've asked this a long time ago (at the same time we added Uber by name to the JanusGraph README) and it was declined. Trust me, I would have loved to add this way back when if this would be possible.

**Comment by porunov** [comment]
@mbrukman have you asked the permission from Uber B.V. office ? I am trying to find a correct way to ask the permission. I would like to leave this PR for permission tracking.

**Comment by porunov** [comment]
Linking Uber brand here: https://brand.uber.com/
Haven't yet research what are the terms of usage.

**Comment by FlorianHockmann** [comment]
Any updates on this? Otherwise I'd say we close this for now and reopen / create a new PR in case we get the approval at some point in the future.
@porunov @mbrukman

**Comment by porunov** [comment]
Agree. We didn't get the approval here.

**Pull request closed without merging**
