### PR TITLE
Add Linkurious logo to list of production users

### PR DESCRIPTION
**Pull request by francescoinfante**
Preview of how it would look like:
schermata_2018-02-14_alle_18 58 56

@davidrapin

### CODE REVIEW

**Comment by francescoinfante** [comment]
@mbrukman should I sign the CLA to propose this change?

**Comment by mbrukman** [comment]
@francescoinfante — please rebase your change on `master` rather than merging in master, so it's a cleaner commit.

Also, just to clarify: are you saying that Linkurious (the company) is running JanusGraph in production? Or are you saying that customers are deploying Linkurious (the software) + JanusGraph in production? Because those are very different things. What is Linkurious (the company) use case in production with JanusGraph?

The reason I ask is that we've already added Linkurious to our visualization integrations:
https://github.com/janusgraph/janusgraph/#visualization
so I'm curious if this is what you meant to add, rather than the logo here.

**Comment by francescoinfante** [comment]
@mbrukman Our customers deploy JanusGraph in production along with Linkurious. Today, we provide 2 solutions for JanusGraph:
- https://doc.linkurio.us/ogma/latest/tutorials/janusgraph/
  - Our graph visualization library and how to integrate it with JanusGraph
- https://linkurio.us/solution/janusgraph/
  - Our software that we deploy on premise, complete of the drivers needed to support JanusGraph

Let me know if the second solution is fit to put our logo on the JanusGraph website. In negative case, I will create a PR to update the link at https://github.com/janusgraph/janusgraph/#visualization.

**Comment by mbrukman** [comment]
@francescoinfante -- we want to list logos of specific users of JanusGraph rather than logos of service providers (whose customers may or may not use JanusGraph specifically), because users who run Linkurious might not necessarily use JanusGraph (since Linkurious works with several graph databases), and Linkurious doesn't themselves run JanusGraph in production.

So, sounds like it would be best to update the content in  https://github.com/janusgraph/janusgraph/#visualization to better explain your current offerings.

Thanks!

**Pull request closed without merging**
