### PR TITLE
Fix broken online meetup links

### LINKED ISSUE #74: Update JanusGraph Online Meetup links
The current links are broken, see [this thread on janusgraph-users](https://groups.google.com/forum/#!topic/janusgraph-users/YKP8IulcBN0) where Brian Hall from Expero also posted updated links.

### PR DESCRIPTION
**Pull request by FlorianHockmann**
Fixes #74

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
> I see that links to slides disappeared also.

Where slides included there? We can ask Expero whether they can integrate them there again and also whether these links stay up. I think we should link to their site if they can keep the links stable as they hosted the meetups.

**Comment by porunov** [comment]
Past links were including slides of all presentations in addition to video. Currently I see only videos

**Comment by FlorianHockmann** [comment]
OK, I asked Brian about that in the [Google groups thread](https://groups.google.com/forum/#!topic/janusgraph-users/YKP8IulcBN0). Let's see what he responds and then I'll update this PR if needed.

**Comment by FlorianHockmann** [comment]
OK, but unfortunately the Travis build fails. Do you have any idea why? It seems to be caused by this part of the build log:

```
ERROR:  Error installing jekyll:

	There are no versions of jekyll-sass-converter (~> 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?

	jekyll-sass-converter requires Ruby version >= 2.4.0. The current ruby version is 2.3.3.222.

1 gem installed

Fetching gem metadata from https://rubygems.org/..........

Fetching gem metadata from https://rubygems.org/.

Resolving dependencies...

Bundler could not find compatible versions for gem "bundler":

  In Gemfile:

    bundler (~> 2.0.1)

  Current Bundler version:

    bundler (2.1.4)

This Gemfile requires a different version of Bundler.

Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 2.0.1)' in any of the relevant sources:

  the local ruby installation

The command "gem update --system; gem install bundler jekyll; bundle install;" failed and exited with 6 during .
```

If you also have no experience with the Travis build here, then I can also look into this myself. I just hoped that you might already have an idea of how this could be fixed.

**Comment by porunov** [comment]
I don't have much experience with it. I have noticed that TravisCI became broken when something in HitHub has changed (don't remember what. Either version of Jekyil is changed or something else). Even so TravisCI fails, web page updates works as expected

**Comment by porunov** [comment]
@FlorianHockmann I have created an issue about it: #77 
I think it would be good to merge these PRs first and then try to fix TravisCI builds

**Comment by FlorianHockmann** [comment]
>  I have created an issue about it: #77
I think it would be good to merge these PRs first and then try to fix TravisCI builds

Thanks! I just merged it.

**Pull request merged**
