### PR TITLE
Add Netflix logo with link

### PR DESCRIPTION
**Pull request by porunov**
PR should wait for approval for Netflix representatives.

DEMO Preview: https://porunov.github.io/janusgraph.org

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
We've asked this a long time ago (at the same time we added Netflix by name to the JanusGraph README) and it was declined. Trust me, I would have loved to add this way back when if this would be possible.

**Comment by porunov** [comment]
@mbrukman I've send email to `netflixoss@netflix.com` but not sure it is a right channel. Do you know another channel? I would like to ask the permission again.

**Comment by porunov** [comment]
After some researching I've found this terms: https://partner.netflix.com/en/terms/
And this source: https://brand.netflix.com/en/assets/

Right now it isn't clear for me if we should get an approval to use logo or it is OK to use the logo if we are following requirements listed in Terms and Conditions.

**Comment by porunov** [comment]
We didn't get the approval here. So I am closing this PR

**Pull request closed without merging**
