### PR TITLE
Remove Seeq logo

### PR DESCRIPTION
**Pull request by sharpau**
Seeq is no longer using JanusGraph in production.

Goes with https://github.com/JanusGraph/janusgraph/pull/1101

### CODE REVIEW

**Comment by sharpau** [comment]
Blargh, I am real bad about remembering the -s switch to git commit. Hopefully latest commit has it all (and I removed the logo). I did it from the same machine I did the other PR, so I'm not sure why (other than missing -s) it would use a different email.

**Comment by mbrukman** [comment]
@sharpau — looks like [the email used in your commit](https://github.com/JanusGraph/janusgraph.org/pull/44.patch) does not match the email listed the [Seeq CCLA](https://github.com/JanusGraph/legal/blob/9f287d7673925081d8d0f91bd1914175c1ed2f89/CLA_SIGNERS.yaml#L437).

You previously used the email address in [your other PR](https://patch-diff.githubusercontent.com/raw/JanusGraph/janusgraph/pull/1101.patch) that's listed in the CCLA, so it was immediately validated.

**Comment by mbrukman** [comment]
@sharpau — any issues with fixing the email address in your commit so that it can be validated and we can merge it? Or would you like to close this PR and have me make this change?

**Comment by sharpau** [comment]
I am not sure why the email address is different. Feel free to decline this
PR and do it yourself.

**Comment by mbrukman** [comment]
Replacing this PR with https://github.com/JanusGraph/janusgraph.org/pull/49.

**Pull request closed without merging**
