### PR TITLE
Added 2 JanusGraph presentations to index.md

### PR DESCRIPTION
**Pull request by sumalaika**
Signed-off-by: Susan Malaika <malaika@us.ibm.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
OK, I don't know what's going on here, @sumalaika -- it looks like [your commit](https://github.com/JanusGraph/janusgraph.org/pull/26.patch) exactly matches what's in [`CLA_SIGNERS.yaml`](https://github.com/JanusGraph/legal/blob/5282fe3fa251f79aed776a8f09e58acde5d77cd9/CLA_SIGNERS.yaml#L262-L264).

Let me investigate this further, no need for you to do anything at this time. Sorry for the trouble!

**Comment by sumalaika** [comment]
@mbrukman - any news? can I proceed?

**Comment by sumalaika** [comment]
@mbrukman - I'd like to add lists of presentations. Can I proceed?

**Comment by mbrukman** [comment]
@sumalaika — sorry for the delay. This looks like an issue in GitHub API: the PR submitter is not being recorded, so it cannot be programmatically verified, even though it's clear (to a human) that you're the author of this PR via the GitHub UI. I will file a support ticket with GitHub and cc: you on it.

We've seen this happen in the past; it's something that only GitHub admins can fix for us.

**Comment by mbrukman** [comment]
Previous instance when this happened as well: https://github.com/JanusGraph/janusgraph/pull/96#issuecomment-278775904

I've filed a support ticket with GitHub requesting them to fix it as they did previously, and asked how we can avoid this issue in the future. @sumalaika: I've cc'd you in the report; not sure if that means you'll be cc'd on the email and their responses as well.

**Comment by mbrukman** [comment]
Update: GitHub support replied, I provided more information on what is the issue. For future reference, the concrete issue here is:

If we look at [commits for PR #26](https://github.com/JanusGraph/janusgraph.org/pull/26/commits), we find a [single commit](https://github.com/JanusGraph/janusgraph.org/pull/26/commits/e6237b69cc1d3857a32166930f3a5c6380d8b512) and looking at what [the API returns for this commit](https://api.github.com/repos/sumalaika/janusgraph.org/commits/e6237b69cc1d3857a32166930f3a5c6380d8b512), we see:

```json
"author": null,
"committer": null,
```

In contrast, looking at [commits for PR #27](https://github.com/JanusGraph/janusgraph.org/pull/27/commits), we also find a [single commit](https://github.com/JanusGraph/janusgraph.org/pull/27/commits/f6ca5626c657430792d03a81e1098b468ee675e4) and looking at what [the API returns for this commit](https://api.github.com/repos/mbrukman/janusgraph.org/commits/f6ca5626c657430792d03a81e1098b468ee675e4), we see that it is a much more complete response:

```
"author": {
  "login": "mbrukman",
  [...lots more here...]
},
"committer": {
  "login": "mbrukman",
  [...lots more here...]
},
```

GitHub support mentioned that last time that happened (in the previous instance I mentioned earlier), the developer did not associate their email address with their GitHub account. @sumalaika, did you associate your work email address with your GitHub account?

**Comment by mbrukman** [comment]
This PR partially addresses issue #23.

**Pull request merged**
