### PR TITLE
fixed typo in README [skip ci]

### PR DESCRIPTION
**Pull request by chupman**
Signed-off-by: Chris Hupman <chupman@us.ibm.com>

### CODE REVIEW

**Comment by mbrukman** [comment]
Thanks for the fix!

**Comment by mbrukman** [comment]
Do you want to target `0.2` here and then bring it into `master` so that they don't diverge?

**Comment by chupman** [comment]
@mbrukman this is the readme for the janusgraph.org repo, not the main repo and it doesn't have any branches. I'll retarget the other PR though.

**Comment by mbrukman** [comment]
Ah, sorry, my bad. You're absolutely right.

**Pull request merged**
