### PR TITLE
Add Aerospike storage adapter

### PR DESCRIPTION
**Pull request by porunov**
Add Aerospike storage adapter.
Sort adapters in lexicographic order.

DEMO Preview: https://porunov.github.io/janusgraph.org

Signed-off-by: Oleksandr Porunov <alexandr.porunov@gmail.com>

### CODE REVIEW

**Comment by FlorianHockmann** [comment]
@porunov Did you see [this comment](https://github.com/Playtika/aerospike-janusgraph-storage-backend/issues/25#issuecomment-494941896) in their repo?
It looks like they don't consider it production ready yet. So, we shouldn't advertise it in our homepage.

**Comment by porunov** [comment]
@FlorianHockmann thank you for finding this comment. I didn't check issues.
You are right. We should wait till it is production ready.

**Comment by kptfh** [comment]
Connector has been working on PROD for more then 3 months. 
Currently it works only in CONSISTENT mode (like ATOMIC_BATCH_MUTATE in Cassandra).

**Comment by porunov** [comment]
Thank you @kptfh for the notification! LGTM from me.

**Pull request merged**
