### PR TITLE
Add Times Internet logo to the list of users.

### PR DESCRIPTION
**Pull request by mbrukman**
/cc: @pankajydv — please review and approve.

Adding per request from @pankajydv; see [use case description via `janusgraph-users@`][1].

Here's a [preview][2] of what this will look like once submitted.

[1]: https://groups.google.com/d/msg/janusgraph-users/HK88QIGRpnY/FNK5t4eDBAAJ
[2]: https://mbrukman.github.io/janusgraph.org/#users

### CODE REVIEW

**Comment by pankajydv** [comment]
@mbrukman This looks good to me :+1:

**Comment by mbrukman** [comment]
@pankajydv wrote:

> alt="Seeq" part should be changed to alt="Times Internet"

My apologies, of course it should! Sorry about the late-night copy-paste error. Fixed.

> My apologies, the correct logo is https://github.com/pankajydv/timesinternet/raw/master/timesinternet_logo.png. The product team has told me that the earlier logo (in 2 lines) is not the correct one, our logo is on one line.

Also fixed in the latest update, but the logo is now quite small because it's so wide (a two-line logo looks better at smaller sizes). I'm experimenting with making it more readable by making it wider; will post an update once I have something better.

**Comment by pankajydv** [comment]
Thanks for your efforts @mbrukman.

**Comment by mbrukman** [comment]
Updated logo width to be 250px so that it looks nicer; see [preview][1] for the latest version.

Ready for review and merge.

[1]: https://mbrukman.github.io/janusgraph.org/#users

**Comment by pankajydv** [comment]
Hi, @amcp / @pluradj can you please approve. The other pull request for adding TimesInternet as production users is already merged. Please merge this logo as well. Thanks.

**Comment by mbrukman** [comment]
FYI, @pankajydv, I updated the URL behind the Times Internet logo to point to the JanusGraph blog post so it points to the same blog post as in https://github.com/JanusGraph/janusgraph/#users and folks can get the same context regarding the JanusGraph use case — is that OK?

**Comment by pankajydv** [comment]
Yes that's absolutely fine. Thanks!

**Pull request merged**
