### PR TITLE
Added G.V() - Gremlin IDE to features.html (#93)

### PR DESCRIPTION
**Pull request by gdotv**
Added G.V() - Gremlin IDE to the support visualization tools.

### CODE REVIEW

**Comment by gdotv** [comment]
Apologies, it appears I've messed up linking the issue I've created against janusgraph.org's main repository, it's https://github.com/JanusGraph/janusgraph.org/issues/93.

**Review by FlorianHockmann — APPROVED** [review]

**Comment by gdotv** [comment]
Hey I've just realised this fell off my plate for a while.
I've fixed the conflict with the latest version on the Key Lines link (was https://cambridge-intelligence.com/visualizing-janusgraph-new-titandb-fork on my version, updated to https://cambridge-intelligence.com/keylines/janusgraph as seen on master).
Can this be looked into for merge/deploy? Could definitely use a direct link from janusgraph's website!

Cheers,
Arthur

**Comment by FlorianHockmann** [comment]
Hey Arthur, thanks for getting back on this. I actually also forgot about this completely. I could have just merged it in January already. Sorry for that!

Could you please delete your last commit here where you merged `master` into your own branch and instead rebase on master?
The steps for rebasing should be simply:

```bash
git rebase origin/master
# fix merge conflicts
git push -f
```

**Comment by gdotv** [comment]
Hey Florian, thanks for getting back so quick. I think this should do it this time? Let me know. Apologies, I'm still not super familiar with these processes so I hope I did all this right!

**Comment by FlorianHockmann** [comment]
Unfortunately this still doesn't look good. There's still a merge conflict and 2 commits instead of just one. Could you please try the following steps?

1. First ensure that you are on your feature branch and have the latest changes from the JanusGraph repo (assuming that it's called `origin`):
```bash
git checkout gdotv-readme
git fetch origin
```

2. Save your own changes so you can apply them back later:
```bash
git reset HEAD~2
git stash
```

3. Rebase on `master` from `origin` to get the latest changes in:
```bash
git rebase origin/master
```

4. Apply your own changes that you saved in step 2. You may need to resolve merge conflicts here:
```bash
git stash apply
```

5. After you have resolved merge conflicts, create a new commit:
```bash
git commit -s
```

6. Force push your updated branch which should now have just one commit on top of `master`:
```bash
git push -f
```

### 2nd Option

Since your change just changes a single line, it could also be easier to just do a hard reset instead on `master` and then make your change again and commit & force push that. 
In that case, it should just be:

```bash
git checkout gdotv-readme
git fetch origin
git reset --hard origin master
# apply your change
git commit -s
git push -f
```

**Comment by FlorianHockmann** [comment]
No problem. Everything looks good now, so I'm merging this.

**Pull request merged**
